records/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse
from . import views

urlpatterns = patterns('',
    url(r'^patients/$', views.PatientList.as_view(), name='patient_list'),
    url(r'^patients-json/$', views.patient_list_json), 
    #url(r'^patient/add/$', views.PatientAddForm.as_view(), name='patient_add'),
    url(r'^patient/(?P<slug>[-\w]+)/$', views.PatientDetail.as_view(), name='patient_detail'),
    url(r'^patient/(?P<slug>[-\w]+)/add-medication/$', views.MedicationAdd.as_view(), name='med_add'),
    url(r'^patient/(?P<slug>[-\w]+)/add-surgery/$', views.SurgeryAdd.as_view(), name='surgery_add'),
    url(r'^patient/(?P<slug>[-\w]+)/add-seizure/$', views.SeizureAdd.as_view(), name='seizure_add'),
    url(r'^visual/$', views.patient_visual),
)

rmh_epilepsy/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from rest_framework import routers
from records import views

router=routers.DefaultRouter()
router.register(r'patients', views.PatientViewSet) 

urlpatterns = patterns('',
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^records/', include('records.urls')),
    url(r'^', include(router.urls)),
 	)

records/models.py
from django.core.urlresolvers import reverse
from django.db import models

class Patient(models.Model):
    name = models.CharField(max_length=60, blank=True, null=True)
    anon_number = models.CharField(max_length=10)
    slug = models.SlugField()

    def get_absolute_url(self):
        return reverse('patient_detail', args=[self.slug])

    def save(self):
        self.slug = self.anon_number
        super(Patient, self).save() 

    def __unicode__(self):
        return self.anon_number

SURGERY_CHOICES = (
    ('0', 'Anterior temporal lobectomy'),
    ('1', 'Other temporal resection'),
    ('2', 'Extra temporal resection'),
    ('3', 'Repeat resecetion'),
    ('4', 'Vagal nerve stimulator'),
    ('5', 'Temporal lesionectomy'),
    ('6', 'Further resection'),)



class Surgery(models.Model):
    date = models.DateField()
    surgery_type = models.CharField(max_length=1, choices=SURGERY_CHOICES)
    patient = models.ForeignKey(Patient, related_name='surgeries')

    def get_absolute_url(self):
        return reverse('patient_detail', args=[self.patient.slug])

    def __unicode__(self):
        return '%s %s' %(self.date, self.get_surgery_type_display())

SEIZURE_CHOICES = (
('1', 'Seizure-free, need for antiepileptic drug unknown'),
('2', 'Seizure-free, requires antiepileptic drugs to remain so'),
('3', 'Nondisabling simple partial seizures only'),
('4', 'Nondisabling nocturnal seizures only'),
('5', '1 - 3 per year'),
('6', '4 - 11 per year'),
('7', '1 - 3 per month'),
('8', '1 - 6 per week'),
('9', '1 - 3 per day'),
('10', '4 - 10 per day'),
('11', '> 10 per day but not status epilepticus'),
('12','Status epilepticus without barbiturate coma'),)

SEVERITY_CHOICES = (
('0', 'Nocternal'),
('1', 'Not Disabling'),
('2', '?1'),
('3', 'Short, brief, disabling'),
('4', '?2'),
('5', 'Convulsion'),
)

EVENT_CONFIDENCE_CHOICES = (
('0', 'Definitely not an epileptic event'),
('1', 'Unsure if epileptic'),
('2', '?1'),
('3', 'Possibly epileptic'),
('4', '?2'),
('5', 'Epileptic seizure'),
)

class Seizure(models.Model):
    assessment_date = models.DateField()
    frequency = models.CharField(max_length=2, choices=SEIZURE_CHOICES) 
    episode_severity = models.CharField(max_length=1, choices=SEVERITY_CHOICES, blank=True)
    event_confidence = models.CharField(max_length=1, choices=EVENT_CONFIDENCE_CHOICES, blank=True)
    patient = models.ForeignKey(Patient, related_name='seizures')

    def get_absolute_url(self):
        return reverse('patient_detail', args=[self.patient.slug])

    def __unicode__(self):
        return '%s %s' %(self.assessment_date, self.get_episode_severity_display())

DOSE_UNIT_CHOICES = (
('0', 'ug'),
('1', 'mg'),
('2', 'g'),
('3', 'ml'),
('4', 'drop'),
)

MED_FREQ_CHOICES = (
('qid', 'Four a day'),
('bd', 'Twice a day'),
('tds', 'Three times a day'),
('man', 'Morning'),
('mid', 'Midday'), 
('noc', 'Night'),
('prn', 'As required'),
('dai', 'Daily'),
)

class Medication(models.Model):
    patient = models.ForeignKey(Patient, related_name='medications')
    dosage = models.IntegerField()
    dose_unit = models.CharField(max_length=1, choices=DOSE_UNIT_CHOICES)   
    frequency = models.CharField(max_length=4, choices=MED_FREQ_CHOICES)
    name = models.CharField(max_length=20)
    date = models.DateField()
    no_medications = models.BooleanField(default=False)  
    
    def get_absolute_url(self):
        return reverse('patient_detail', args=[self.patient.slug])

   

records/forms.py
from django import forms
from django.conf import settings
from django.forms.extras.widgets import SelectDateWidget

from .models import Seizure, Surgery, Medication

'''
Date Widgets
'''
class CalendarWidget(forms.TextInput):
    class Media:
        css = {
            'all': (settings.STATIC_URL + 'css/datepicker.css',)
        }
        js = (settings.STATIC_URL + 'js/bootstrap-datepicker.js',settings.STATIC_URL + 'js/calendar.js')

class CalendarDayWidget(forms.TextInput):
    class Media:
        css = {
            'all': (settings.STATIC_URL + 'css/datepicker.css',)
        }
        js = (settings.STATIC_URL + 'js/bootstrap-datepicker.js',settings.STATIC_URL + 'js/calendar-day.js')

class MedicationAddForm(forms.ModelForm):
    class Meta:
        model = Medication
        widgets = {
            'patient':forms.Select(attrs={'class':'form-control'}),
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'dosage':forms.NumberInput(attrs={'class':'form-control'}),
            'dose_unit':forms.Select(attrs={'class':'form-control'}),
            'frequency':forms.Select(attrs={'class':'form-control'}),
            'date':CalendarWidget(attrs={'class':'input-append form-control', 'placeholder':'YYYY-MM-DD'}),
            'no_medications':forms.CheckboxInput(attrs={'class':'form-control'}),
       }  
    
class SeizureAddForm(forms.ModelForm):
    class Meta:
        model = Seizure
        widgets = {
            'patient':forms.Select(attrs={'class':'form-control'}),
            'assessment_date': CalendarWidget(attrs={'class':'input append form-control'}),
            'frequency': forms.Select(attrs={'class':'form-control'}),
            'episode_severity':forms.Select(attrs={'class':'form-control'}),
            'event_confidence':forms.Select(attrs={'class':'form-control'}),
        }

class SurgeryAddForm(forms.ModelForm):
    class Meta:
        model = Surgery
        widgets = {
            'patient':forms.Select(attrs={'class':'form-control'}),
            'date': CalendarWidget(attrs={'class':'input-append form-control', 'placeholder':'YYYY-MM-DD'}),
            'surgery_type': forms.Select(attrs={'class':'form-control'}),
        }

records/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import generic
from django.views.decorators.csrf import csrf_exempt

from .models import Patient, Seizure, Medication, Surgery
from .serializers import PatientSerializer, SeizureSerializer 
from .forms import MedicationAddForm, SeizureAddForm, SurgeryAddForm

from rest_framework import viewsets
from rest_framework.parsers import JSONParser
from rest_framework.renderers import JSONRenderer

import datetime

class JSONResponse(HttpResponse):
    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)
        kwargs['content_type'] = 'application/json'
        super(JSONResponse, self).__init__(content, **kwargs)

@csrf_exempt
def patient_list_json(request):
    if request.method =='GET':
        patients = Patient.objects.all()
        serializer = PatientSerializer(patients, many=True)
        return JSONResponse(serializer.data)


def patient_visual(request):
        return render(request, 'records/patient_visual.html')


class PatientViewSet(viewsets.ModelViewSet):
    queryset = Patient.objects.all()
    serializer_class = PatientSerializer


class PatientDetail(generic.DetailView):
    model = Patient


class PatientList(generic.ListView):
    model = Patient


class PatientForm(generic.FormView):
    model = Patient


class MedicationAdd(generic.CreateView):
    fields = ['patient', 'dosage','dose_unit','frequency','name','date','no_medication']
    form_class = MedicationAddForm
    model = Medication
    
    def get_initial(self):
        slug = self.kwargs['slug']
        patient = Patient.objects.get(slug=slug)
        return {'patient': patient.id }


class SeizureAdd(generic.CreateView):
    fields = ['patient', 'assessment_date','frequency','episode_severity','event_confidence']
    form_class = SeizureAddForm
    model = Seizure
    
    def get_initial(self):
        slug = self.kwargs['slug']
        patient = Patient.objects.get(slug=slug)
        date = datetime.datetime.today().strftime("%Y-%m-%d")
        print date, patient
        return {'patient': patient.id, 'assessment_date':date, }


class SurgeryAdd(generic.CreateView):
    fields = ['patient', 'date','surgery_type']
    form_class = SurgeryAddForm
    model = Surgery

    def get_initial(self):
        slug = self.kwargs['slug']
        patient = Patient.objects.get(slug=slug)
        return {'patient': patient.id }

templates/records/medication_form.html
{% extends "base.html" %}
{% load staticfiles %}


{% block stylesheets %}
{{ block.super }}
  {{ form.media.css }}
{% endblock stylesheets %}

{% block javascript %}
{{ block.super }}
  {{ form.media.js }}
{% endblock javascript %}

{% block content %}
<h1>Add Medication</h1>

<div class="col-md-6 form-horizontal">
    <form action="" method="post" role="form">{% csrf_token %} 
        
        <div class="hidden">{{ form.patient }}</div>

      <div class="form-group"> 
      <div class="col-md-4 control-label">Name</div>
      <div class="col-md-5">{{ form.name }}</div>
      </div>

      <div class="form-group"> 
      <div class="col-md-4 control-label">Dosage</div>
      <div class="col-md-5">{{ form.dosage }}</div>
      </div>

      <div class="form-group"> 
      <div class="col-md-4 control-label">Dose Unit</div>
      <div class="col-md-5">{{ form.dose_unit }}</div>
      </div>

      <div class="form-group"> 
      <div class="col-md-4 control-label">Frequency</div>
      <div class="col-md-5">{{ form.frequency }}</div>
      </div>

      <div class="form-group"> 
      <div class="col-md-4 control-label">Date</div>
      <div class="col-md-5">{{ form.date }}</div>
      </div>

      <div class="form-group"> 
      <div class="col-md-4 control-label">No Medications?</div>
      <div class="col-md-5">{{ form.no_medications }}</div>
      </div>

    </div>

    <div class="col-md-6 form-horizontal">
  <button type="submit" class="btn btn-primary">Add Medication</button>
  </form>
</div>
{% endblock content %}

templates/records/patient_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="row">
<h4>Patient Details</h4>

  <div class="col-md-6">
  <p><strong>Name:</strong>{{ object.name }}</p>
  <p><strong>Anon number:</strong>{{ object.anon_number }}</p>
  </div>
  <div class="col-md-6">
    <a type="button" class="btn btn-info" href="{{ object.get_absolute_url }}add-medication/">Add Medication</a>
    <a type="button" class="btn btn-danger" href="{{ object.get_absolute_url }}add-seizure/">Add Seizure</a>
    <a type="button" class="btn btn-warning" href="{{ object.get_absolute_url }}add-surgery/">Add Surgery</a>
  </div>
  <div class="col-md-12">
    {% if object.medications.all|length > 0 %}
    <h4>Medications</h4>
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>Medication Name</th>
                <th>Date</th>
                <th>Dosage</th>
                <th>Frequency</th>
                <th>Medications</th>
            </tr>
        </thead>
        <tbody>
            {% for medication in object.medications.all %}
            <tr>
                <td>{{ medication.name }}</a></td>
                <td>{{ medication.date|date:"d/m/y" }}</td>
                <td>{{ medication.dosage }} {{ medication.get_dose_unit_display }}</td>
                <td>{{ medication.frequency }}</td>
                <td>{{ medication.no_medication }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
    {% if object.seizures.all|length > 0 %}
    <h4>Seizures</h4>
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>Frequency</th>
                <th>Date</th>
                <th>Episode Severity</th>
                <th>Event Confidence</th>
            </tr>
        </thead>
        <tbody>
            {% for seizure in object.seizures.all %}
            <tr>
                <td>{{ seizure.get_frequency_display }}</a></td>
                <td>{{ seizure.date|date:"d/m/y" }}</td>
                <td>{{ seizure.get_episode_severity_display }}</td>
                <td>{{ seizure.get_event_confidence_display }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
    {% if object.surgeries.all|length > 0 %}
    <h4>Surgeries</h4>
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>Date</th>
                <th>Surgery Type</th>
            </tr>
        </thead>
        <tbody>
            {% for surgery in object.surgeries.all %}
            <tr>
                <td>{{ surgery.date|date:"d/m/y" }}</td>
                <td>{{ surgery.get_surgery_type_display }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/records/patient_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<h2>Patients</h2>
<table class="table table-striped table-hover">
  <caption></caption>
  <thead>
    <tr>
      <th>Name</th>
      <th>Anon ID</th>
    </tr>
  </thead>
  <tbody>
        {% for patient in object_list %}
        <tr>
            <td><a href="{{ patient.get_absolute_url }}">{{ patient.name }}</a></td>
            <td>{{ patient.anon_number }}</td>
        </tr>
        {% endfor %}
  </tbody>
</table>

{% if is_paginated %}
    <div class="pagination">
        <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
    </div>
{% endif %}


{% endblock %}

templates/records/patient_visual.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>EpilepsyProject</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <base href="/records/visual">
    <meta name="epilepsy-project/config/environment" content="%7B%22modulePrefix%22%3A%22epilepsy-project%22%2C%22environment%22%3A%22production%22%2C%22baseURL%22%3A%22/%22%2C%22locationType%22%3A%22auto%22%2C%22EmberENV%22%3A%7B%22FEATURES%22%3A%7B%7D%7D%2C%22APP%22%3A%7B%7D%7D">

    <link rel="stylesheet" href="{% static "assets/vendor.css" %}">
    <link rel="stylesheet" href="{% static "assets/app.css" %}">
    <link rel="stylesheet" href="{% static "assets/epilepsy-project.css" %}">
  </head>
  <body>
    <script src="{% static "assets/vendor.js" %}"></script>
    <script src="{% static "assets/epilepsy-project.js" %}"></script>
  </body>
</html>

templates/records/seizure_form.html
{% extends "base.html" %}
{% load staticfiles %}


{% block stylesheets %}
{{ block.super }}
  {{ form.media.css }}
{% endblock stylesheets %}

{% block javascript %}
{{ block.super }}
  {{ form.media.js }}
{% endblock javascript %}

{% block content %}
<h1>Add Seizure Record</h1>
{{ patient }}
{{ assessment_date }}
<div class="col-md-6 form-horizontal">
    <form action="" method="post" role="form">{% csrf_token %} 
        <div class="hidden">{{ form.patient }}</div>
      <div class="form-group">
      <div class="col-md-4 control-label">Assessment Date</div>
      <div class="col-md-5">{{ form.assessment_date }}</div>
      </div>

      <div class="form-group"> 
      <div class="col-md-4 control-label">Frequency</div>
      <div class="col-md-5">{{ form.frequency }}</div>
      </div>

      <div class="form-group"> 
      <div class="col-md-4 control-label">Episode Severity</div>
      <div class="col-md-5">{{ form.episode_severity }}</div>
      </div>

      <div class="form-group"> 
      <div class="col-md-4 control-label">Event Confidence</div>
      <div class="col-md-5">{{ form.event_confidence }}</div>
      </div>

    </div>

    <div class="col-md-6 form-horizontal">


  <button type="submit" class="btn btn-primary">Add Seizure</button>
  </form>
</div>
{% endblock content %}

templates/records/surgery_form.html
{% extends "base.html" %}
{% load staticfiles %}


{% block stylesheets %}
{{ block.super }}
  {{ form.media.css }}
{% endblock stylesheets %}

{% block javascript %}
{{ block.super }}
  {{ form.media.js }}
{% endblock javascript %}

{% block content %}
<h1>Add Surgery</h1>

<div class="col-md-6 form-horizontal">
    <form action="" method="post" role="form">{% csrf_token %} 
        <div class="hidden">{{ form.patient }}</div>

      <div class="form-group"> 
      <div class="col-md-4 control-label">Date</div>
      <div class="col-md-5">{{ form.date }}</div>
      </div>

      <div class="form-group"> 
      <div class="col-md-4 control-label">Surgery Type</div>
      <div class="col-md-5">{{ form.surgery_type }}</div>
      </div>
    </div>

    <div class="col-md-6 form-horizontal">

  <button type="submit" class="btn btn-primary">Add Surgery</button>
  </form>
</div>
{% endblock content %}